// Code generated by protoc-gen-go. DO NOT EDIT.
// source: receive_rpc.proto

package receive_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MsgResp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgResp) Reset()         { *m = MsgResp{} }
func (m *MsgResp) String() string { return proto.CompactTextString(m) }
func (*MsgResp) ProtoMessage()    {}
func (*MsgResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f4573fa008d808, []int{0}
}

func (m *MsgResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgResp.Unmarshal(m, b)
}
func (m *MsgResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgResp.Marshal(b, m, deterministic)
}
func (m *MsgResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgResp.Merge(m, src)
}
func (m *MsgResp) XXX_Size() int {
	return xxx_messageInfo_MsgResp.Size(m)
}
func (m *MsgResp) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgResp.DiscardUnknown(m)
}

var xxx_messageInfo_MsgResp proto.InternalMessageInfo

func (m *MsgResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *MsgResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type Msg struct {
	Id                   int64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Resp                 []*MsgResp `protobuf:"bytes,2,rep,name=resp,proto3" json:"resp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f4573fa008d808, []int{1}
}

func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (m *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(m, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Msg) GetResp() []*MsgResp {
	if m != nil {
		return m.Resp
	}
	return nil
}

func init() {
	proto.RegisterType((*MsgResp)(nil), "rpc.MsgResp")
	proto.RegisterType((*Msg)(nil), "rpc.Msg")
}

func init() { proto.RegisterFile("receive_rpc.proto", fileDescriptor_a5f4573fa008d808) }

var fileDescriptor_a5f4573fa008d808 = []byte{
	// 141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x4a, 0x4d, 0x4e,
	0xcd, 0x2c, 0x4b, 0x8d, 0x2f, 0x2a, 0x48, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e,
	0x2a, 0x48, 0x56, 0xd2, 0xe7, 0x62, 0xf7, 0x2d, 0x4e, 0x0f, 0x4a, 0x2d, 0x2e, 0x10, 0x12, 0xe2,
	0x62, 0x49, 0xce, 0x4f, 0x49, 0x95, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x02, 0xb3, 0x85, 0x04,
	0xb8, 0x98, 0x73, 0x8b, 0xd3, 0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0x40, 0x4c, 0x25, 0x73,
	0x2e, 0x66, 0xdf, 0xe2, 0x74, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0xb0, 0x52, 0xe6, 0x20, 0xa6,
	0xcc, 0x14, 0x21, 0x05, 0x2e, 0x96, 0xa2, 0xd4, 0xe2, 0x02, 0x09, 0x26, 0x05, 0x66, 0x0d, 0x6e,
	0x23, 0x1e, 0x3d, 0x90, 0x35, 0x50, 0x83, 0x83, 0xc0, 0x32, 0x49, 0x6c, 0x60, 0x5b, 0x8d, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x2b, 0xca, 0x3b, 0xfb, 0x8a, 0x00, 0x00, 0x00,
}
